common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *common
  database: vad_development

test:
  <<: *common
  database: vad_test

production:
  <<: *common
  database: vad_production
